// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prescription_microservice.Infrastructure.Persistence;

#nullable disable

namespace Prescription_microservice.Migrations
{
    [DbContext(typeof(PrescriptionDbContext))]
    partial class PrescriptionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prescription_microservice.Domain.Entities.InteractionDetectee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ContourneeAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ContourneePar")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("EstContournee")
                        .HasColumnType("bit");

                    b.Property<string>("Justification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mecanisme")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MedicamentA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MedicamentB")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Recommandation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Severite")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("Severite");

                    b.ToTable("Interactions");
                });

            modelBuilder.Entity("Prescription_microservice.Domain.Entities.LignePrescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DCI")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DureeJours")
                        .HasColumnType("int");

                    b.Property<Guid>("MedicamentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NbRenouvellements")
                        .HasColumnType("int");

                    b.Property<string>("NomMedicament")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<bool>("Renouvellement")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("Lignes");
                });

            modelBuilder.Entity("Prescription_microservice.Domain.Entities.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CabinetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConsultationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DateValidation")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DossierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MedecinId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotifRefus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NumeroPrescriptionGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("TypePrescription")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ValiditeJours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumeroPrescriptionGuid")
                        .IsUnique();

                    b.HasIndex("PatientId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("Prescription_microservice.Domain.Entities.InteractionDetectee", b =>
                {
                    b.HasOne("Prescription_microservice.Domain.Entities.Prescription", null)
                        .WithMany("Interactions")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Prescription_microservice.Domain.Entities.LignePrescription", b =>
                {
                    b.HasOne("Prescription_microservice.Domain.Entities.Prescription", null)
                        .WithMany("Lignes")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Prescription_microservice.Domain.ValueObjects.Posologie", "Posologie", b1 =>
                        {
                            b1.Property<Guid>("LignePrescriptionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Dose")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Dose");

                            b1.Property<string>("Frequence")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Frequence");

                            b1.Property<int>("Moment")
                                .HasColumnType("int")
                                .HasColumnName("Moment");

                            b1.Property<string>("Unite")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Unite");

                            b1.HasKey("LignePrescriptionId");

                            b1.ToTable("Lignes");

                            b1.WithOwner()
                                .HasForeignKey("LignePrescriptionId");
                        });

                    b.Navigation("Posologie")
                        .IsRequired();
                });

            modelBuilder.Entity("Prescription_microservice.Domain.Entities.Prescription", b =>
                {
                    b.OwnsOne("NumeroPrescription", "NumeroPrescription", b1 =>
                        {
                            b1.Property<Guid>("PrescriptionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valeur")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("NumeroPrescription");

                            b1.HasKey("PrescriptionId");

                            b1.ToTable("Prescriptions");

                            b1.WithOwner()
                                .HasForeignKey("PrescriptionId");
                        });

                    b.Navigation("NumeroPrescription")
                        .IsRequired();
                });

            modelBuilder.Entity("Prescription_microservice.Domain.Entities.Prescription", b =>
                {
                    b.Navigation("Interactions");

                    b.Navigation("Lignes");
                });
#pragma warning restore 612, 618
        }
    }
}
