version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: API_Gateway-microservice/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Hosts__Auth=auth-microservice
      - Hosts__Patient=patient-microservice
      - Jwt__Key=VOTRE_CLE_SECRETE_LONGUE_32_CHARS
      - Jwt__Issuer=DMI.Auth
      - Jwt__Audience=DMI.Client
    depends_on:
      - auth-microservice
      - patient-microservice
    networks:
      - digihealth-net

  auth-microservice:
    build: ./Auth-microservice
    ports:
      - "5202:8080"
    networks:
      - digihealth-net

  patient-microservice:
    build: ./Patient-microservice
    ports:
      - "5100:8080"
    networks:
      - digihealth-net

networks:
  digihealth-net:
    driver: bridge