// <auto-generated />
using System;
using Dossier_Medical_microservice.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dossier_Medical_microservice.Migrations
{
    [DbContext(typeof(DossierDbContext))]
    partial class DossierDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dossier_Medical_microservice.Domain.Entities.Consultation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Conclusion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateCloture")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DossierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("RendezVousId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("TypeConsultation")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("DossierId");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("Dossier_Medical_microservice.Domain.Entities.Diagnostic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeCIM11")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("EstConfirme")
                        .HasColumnType("bit");

                    b.Property<string>("LibelleCIM11")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CodeCIM11");

                    b.HasIndex("ConsultationId");

                    b.ToTable("Diagnostics");
                });

            modelBuilder.Entity("Dossier_Medical_microservice.Domain.Entities.DocumentMedical", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("DateDocument")
                        .HasColumnType("date");

                    b.Property<Guid>("DossierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TailleOctets")
                        .HasColumnType("bigint");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeDocument")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DossierId");

                    b.HasIndex("TypeDocument");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Dossier_Medical_microservice.Domain.Entities.DossierMedical", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Anamnese")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CabinetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly?>("DateCloture")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateOuverture")
                        .HasColumnType("date");

                    b.Property<Guid>("MedecinId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Dossiers");
                });

            modelBuilder.Entity("Dossier_Medical_microservice.Domain.Entities.LigneOrdonnance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DureeJours")
                        .HasColumnType("int");

                    b.Property<Guid>("MedicamentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomMedicament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrdonnanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Posologie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OrdonnanceId");

                    b.ToTable("LignesOrdonnances");
                });

            modelBuilder.Entity("Dossier_Medical_microservice.Domain.Entities.Ordonnance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Instructions")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ValiditeJours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId");

                    b.ToTable("Ordonnances");
                });

            modelBuilder.Entity("Dossier_Medical_microservice.Domain.Entities.Consultation", b =>
                {
                    b.HasOne("Dossier_Medical_microservice.Domain.Entities.DossierMedical", "DossierMedical")
                        .WithMany("Consultations")
                        .HasForeignKey("DossierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Dossier_Medical_microservice.Domain.ValueObjects.ExamenClinique", "ExamenClinique", b1 =>
                        {
                            b1.Property<Guid>("ConsultationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Observations")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<decimal?>("Poids")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<int?>("Pouls")
                                .HasColumnType("int");

                            b1.Property<string>("TA")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<decimal?>("Taille")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<decimal?>("Temperature")
                                .HasPrecision(4, 1)
                                .HasColumnType("decimal(4,1)");

                            b1.HasKey("ConsultationId");

                            b1.ToTable("Consultations");

                            b1.WithOwner()
                                .HasForeignKey("ConsultationId");
                        });

                    b.Navigation("DossierMedical");

                    b.Navigation("ExamenClinique")
                        .IsRequired();
                });

            modelBuilder.Entity("Dossier_Medical_microservice.Domain.Entities.Diagnostic", b =>
                {
                    b.HasOne("Dossier_Medical_microservice.Domain.Entities.Consultation", "Consultation")
                        .WithMany("Diagnostics")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("Dossier_Medical_microservice.Domain.Entities.DocumentMedical", b =>
                {
                    b.HasOne("Dossier_Medical_microservice.Domain.Entities.DossierMedical", "DossierMedical")
                        .WithMany("Documents")
                        .HasForeignKey("DossierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DossierMedical");
                });

            modelBuilder.Entity("Dossier_Medical_microservice.Domain.Entities.DossierMedical", b =>
                {
                    b.OwnsOne("Dossier_Medical_microservice.Domain.ValueObjects.NumeroDossier", "NumeroDossier", b1 =>
                        {
                            b1.Property<Guid>("DossierMedicalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valeur")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("NumeroDossier");

                            b1.HasKey("DossierMedicalId");

                            b1.HasIndex("Valeur")
                                .IsUnique();

                            b1.ToTable("Dossiers");

                            b1.WithOwner()
                                .HasForeignKey("DossierMedicalId");
                        });

                    b.Navigation("NumeroDossier")
                        .IsRequired();
                });

            modelBuilder.Entity("Dossier_Medical_microservice.Domain.Entities.LigneOrdonnance", b =>
                {
                    b.HasOne("Dossier_Medical_microservice.Domain.Entities.Ordonnance", "Ordonnance")
                        .WithMany("Lignes")
                        .HasForeignKey("OrdonnanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ordonnance");
                });

            modelBuilder.Entity("Dossier_Medical_microservice.Domain.Entities.Ordonnance", b =>
                {
                    b.HasOne("Dossier_Medical_microservice.Domain.Entities.Consultation", "Consultation")
                        .WithMany("Ordonnances")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("Dossier_Medical_microservice.Domain.Entities.Consultation", b =>
                {
                    b.Navigation("Diagnostics");

                    b.Navigation("Ordonnances");
                });

            modelBuilder.Entity("Dossier_Medical_microservice.Domain.Entities.DossierMedical", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Dossier_Medical_microservice.Domain.Entities.Ordonnance", b =>
                {
                    b.Navigation("Lignes");
                });
#pragma warning restore 612, 618
        }
    }
}
