// <auto-generated />
using System;
using Facturation_microservice.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Facturation_microservice.Migrations
{
    [DbContext(typeof(FacturationDbContext))]
    partial class FacturationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Facturation_microservice.Domain.Entities.Facture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConsultationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("DateEcheance")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateFacture")
                        .HasColumnType("date");

                    b.Property<Guid>("MedecinId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ModeReglement")
                        .HasColumnType("int");

                    b.Property<string>("NumeroFacture")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Remise")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<decimal>("TauxTVA")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("NumeroFacture")
                        .IsUnique();

                    b.HasIndex("PatientId");

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("Facturation_microservice.Domain.Entities.LigneFacture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeActe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FactureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrixUnitaire")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<decimal>("TauxRemboursement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeActe")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FactureId");

                    b.HasIndex("TypeActe");

                    b.ToTable("LignesFacture");
                });

            modelBuilder.Entity("Facturation_microservice.Domain.Entities.Paiement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Caissier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FactureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<decimal>("Montant")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("FactureId");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("Facturation_microservice.Domain.Entities.RemboursementCaisse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FactureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModeReglement")
                        .HasColumnType("int");

                    b.Property<decimal>("MontantCaisse")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantComplementaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroAffilie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FactureId")
                        .IsUnique();

                    b.HasIndex("Statut");

                    b.ToTable("Remboursements");
                });

            modelBuilder.Entity("Facturation_microservice.Domain.Entities.LigneFacture", b =>
                {
                    b.HasOne("Facturation_microservice.Domain.Entities.Facture", null)
                        .WithMany("LignesFacture")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Facturation_microservice.Domain.Entities.Paiement", b =>
                {
                    b.HasOne("Facturation_microservice.Domain.Entities.Facture", null)
                        .WithMany()
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Facturation_microservice.Domain.Entities.RemboursementCaisse", b =>
                {
                    b.HasOne("Facturation_microservice.Domain.Entities.Facture", "Facture")
                        .WithOne()
                        .HasForeignKey("Facturation_microservice.Domain.Entities.RemboursementCaisse", "FactureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("Facturation_microservice.Domain.Entities.Facture", b =>
                {
                    b.Navigation("LignesFacture");
                });
#pragma warning restore 612, 618
        }
    }
}
